### PR TITLE
feat(jenkins): support git plugin for slug

### PR DESCRIPTION
**Pull request by krohrsb**
Support creating a `slug` of `owner/repo` given the Jenkins Git plugin is being used.

See the environment variables listed at the bottom of: https://wiki.jenkins.io/pages/viewpage.action?pageId=69273545

### CODE REVIEW

**Comment by krohrsb** [comment]
@pvdlg Are you still active in this repository? I've noticed some other PR's that have been open for a while without feedback as well. Just curious.

**Comment by Aghassi** [comment]
@pvdlg any chance this could get merged? It would help support Jenkins out of box.

**Comment by pvdlg** [comment]
Per the [`GIT_URL` doc](https://wiki.jenkins.io/display/JENKINS/Building+a+software+project):
> For Git-based projects, this variable contains the Git url (like git@github.com:user/repo.git or [https://github.com/user/repo.git])

The code is this PR is not going to work for a lot of Git URL format. Here is a few example:
- `https://github.com/user/repo` => `user/` (if `.git` is missing)
- `https://github.com/repo` => `github.com/` (some git server do not have URL formatted with `user/repo`)

That's just a few example... As it turns out parsing Git URL is quite complex (see https://github.com/IonicaBizau/git-url-parse/blob/master/lib/index.js + all it's dependencies).
We used to use `git-url-parse` in `semantic-release` but we abandoned it due to frequent regression and issues to parse URL of uncommon Git repo (other than GitHub, BitBucket and GitLab).

I don't want to include code in `env-ci` that's going to create either inaccurate values or bugs (due to a dependency for example).
The rule I'm trying to follow is: If the CI provide the info directly include it, if it as to be deducted include it only if we can cover 100% of the cases, otherwise just omit it.

> @pvdlg any chance this could get merged? It would help support Jenkins out of box.

@Aghassi Why do you need those values? In which case it's preventing you to do something?

**Comment by Aghassi** [comment]
@pvdlg When I first made that comment we were looking to rollout supported functionality that would use `env-ci` to determine if we were using CircleCI or Jenkins internally. We have code in place that would allow us to move forward without this change. However, it's still annoying because sometimes we have to tell what CI we are running on and being able to identify helps us make some safe assumptions.

**Comment by pvdlg** [comment]
@Aghassi what does this has to do with returning the `slug` property?

You can already use `env-ci` to determine if you are on CircleCI or Jenkins...
This PR is about returning the `slug` property...

**Comment by Aghassi** [comment]
Ah sorry. Depending on the CI system we operate in, we need the slug. We are using env-CI to get the slugs for the different CIs. But Jenkins is not supported so we had to come up with a way to do it. We wanted to contribute it back so we could rely on this package for that functionality. @krohrsb can also talk to it, we work together.

**Comment by pvdlg** [comment]
The problem, as I mentioned, is that extracting the slug from the repo URL is really not that easy and very error prone.
The code you contributed to this PR might work for the URL format you are using in your specific situation, but it won't work everywhere and it's going to be difficult or nearly impossible to get something that reliably work.

The scope of `env-ci` is essentially to "translate" various CI variable in one common format. Making transformation to deduct some values is out of scope.

So I would recommend that you keep using a custom solution for the parsing the your repo URL which would work as long as you keep URLs the same format.

**Pull request closed without merging**
