### PR TITLE
fix(codebuild): detect branch names

### PR DESCRIPTION
**Pull request by coderbyheart**
It turned out that the branch name detection does not work on CodeBuild. The current version yields head.

This change adds a custom solution for CodeBuild which correctly detects the branch.

If have it running using [this patched version of semantic-release](https://github.com/nRFCloud/semantic-release/commit/56011b1e3ed92b6d989669c13d838128db6a7dcd).

I have verified that it works using a private project:

```

[Container] 2018/04/18 23:15:42 Running command npx semantic-release
[Semantic release]: Running semantic-release version 0.0.0-development
[Semantic release]: Load plugin verifyConditions from @semantic-release/npm
[Semantic release]: Load plugin verifyConditions from @semantic-release/github
[Semantic release]: Load plugin analyzeCommits from @semantic-release/commit-analyzer
[Semantic release]: Load plugin generateNotes from @semantic-release/release-notes-generator
[Semantic release]: Load plugin prepare from @semantic-release/npm
[Semantic release]: Load plugin publish from @semantic-release/npm
[Semantic release]: Load plugin publish from @semantic-release/github
[Semantic release]: Load plugin success from @semantic-release/github
[Semantic release]: Load plugin fail from @semantic-release/github
[Semantic release]: Run automated release from branch saga
[Semantic release]: Call plugin verify-conditions
[Semantic release]: Verify authentication for registry https://registry.npmjs.org/
[Semantic release]: Verify GitHub authentication
[Semantic release]: No git tag version found
[Semantic release]: No previous release found, retrieving all commits
[Semantic release]: Found 1 commits since last release
[Semantic release]: Call plugin analyze-commits
[Semantic release]: Analyzing commit: build(release): use patched version of env-ci
[Semantic release]: The commit should not trigger a release
[Semantic release]: Analysis of 1 commits complete: no release
[Semantic release]: There are no relevant changes, so no new version is released.

[Container] 2018/04/18 23:15:44 Phase complete: POST_BUILD Success: true
[Container] 2018/04/18 23:15:44 Phase context status code: Message: 

```

_Note: we are using a custom branch name there: saga_

### CODE REVIEW

**Comment by pvdlg** [comment]
Can you provide the output of the following commands on CodeBuild:
- `git rev-parse --abbrev-ref HEAD`
- `git rev-parse --abbrev-ref=strict HEAD`
- `git rev-parse --abbrev-ref=loose HEAD`
- `git branch`
- `git branch -a`

Thanks

**Comment by pvdlg** [comment]
To clarify I think this is because CodeBuild create a detached head repo. There might be other CI doing the same so I'd like to find a way to get the current branch that would work for every CI.

**Comment by coderbyheart** [comment]
```
[Container] 2018/04/19 18:31:40 Running command git rev-parse --abbrev-ref HEAD
HEAD

[Container] 2018/04/19 18:31:40 Running command git rev-parse --abbrev-ref=strict HEAD
HEAD

[Container] 2018/04/19 18:31:40 Running command git rev-parse --abbrev-ref=loose HEAD
HEAD

[Container] 2018/04/19 18:31:40 Running command git branch
* (detached from e6ca3ba)
master

[Container] 2018/04/19 18:31:40 Running command git branch -a
* (detached from e6ca3ba)
master
remotes/origin/HEAD -> origin/master
remotes/origin/master
```

**Comment by coderbyheart** [comment]
```
[Container] 2018/04/20 12:51:31 Running command git rev-parse --abbrev-ref HEAD
HEAD

[Container] 2018/04/20 12:51:31 Running command git rev-parse --abbrev-ref=strict HEAD
HEAD

[Container] 2018/04/20 12:51:31 Running command git rev-parse --abbrev-ref=loose HEAD
HEAD

[Container] 2018/04/20 12:51:31 Running command git branch
* (detached from 179d7da)
master

[Container] 2018/04/20 12:51:31 Running command git branch -a
* (detached from 179d7da)
master
remotes/origin/HEAD -> origin/master
remotes/origin/branch-detached-head
remotes/origin/master
```

**Comment by pvdlg** [comment]
I meant, can you test with your semantic-release fork using `pvdlg/env-ci#branch-detached-head` as a dependency to make sure my fix works for you?

**Comment by coderbyheart** [comment]
No, it did not:

```
[Semantic release]: Running semantic-release version 0.0.0-development
[Semantic release]: Load plugin verifyConditions from @semantic-release/npm
[Semantic release]: Load plugin verifyConditions from @semantic-release/github
[Semantic release]: Load plugin analyzeCommits from @semantic-release/commit-analyzer
[Semantic release]: Load plugin generateNotes from @semantic-release/release-notes-generator
[Semantic release]: Load plugin prepare from @semantic-release/npm
[Semantic release]: Load plugin publish from @semantic-release/npm
[Semantic release]: Load plugin publish from @semantic-release/github
[Semantic release]: Load plugin success from @semantic-release/github
[Semantic release]: Load plugin fail from @semantic-release/github
[Semantic release]: This test run was triggered on the branch HEAD, while semantic-release is configured to only publish from saga, therefore a new version won’t be published.
```

I used one of our private packages with this version of semantic release: https://github.com/nRFCloud/semantic-release/commit/dfa78d4909fb6a1d7376b88bdfc89f6c98bbbdaf

**Comment by pvdlg** [comment]
Ok thanks for the test. I tested on a repo with a detached head. I guess there is something different in the way CodeBuild clone the repo.

What do you get on CodeBuild with the command `git show -s --pretty=%D HEAD` ?
Also do you know what command is executed by CodeBuild to clone the repo?

**Comment by coderbyheart** [comment]
I don't know, they don't show you the log, until the source is already available.

```
[Container] 2018/04/22 18:43:28 Running command git rev-parse --abbrev-ref HEAD
HEAD

[Container] 2018/04/22 18:43:29 Running command git rev-parse --abbrev-ref=strict HEAD
HEAD

[Container] 2018/04/22 18:43:29 Running command git rev-parse --abbrev-ref=loose HEAD
HEAD

[Container] 2018/04/22 18:43:29 Running command git branch
* (detached from dfa78d4)
caribou

[Container] 2018/04/22 18:43:29 Running command git branch -a
* (detached from dfa78d4)
caribou
remotes/origin/HEAD -> origin/caribou
remotes/origin/alpaca
remotes/origin/badger
remotes/origin/caribou
remotes/origin/multi-branches
remotes/origin/v7.0.1

[Container] 2018/04/22 18:43:29 Running command git show -s --pretty=%D HEAD
%D
```

**Comment by pvdlg** [comment]
`git show -s --pretty=%D HEAD` should give you the branch from which the detached head was created.
Maybe CodeBuild use an old version of git, so it's why it doesn't works.

What do you get with the following commands:
- `git --version`
- `git log -n 1 --pretty=%D HEAD`
- `git log -n 1 --pretty=%d HEAD`
- `git show -s --pretty=%d HEAD`

**Comment by coderbyheart** [comment]
I use the dockerhub node:8 image, since AWS CodeBuild currently has no Node.js 8 support (they are working on it though).

```

[Container] 2018/04/23 21:49:09 Running command git --version
git version 2.1.4

[Container] 2018/04/23 21:49:09 Running command git log -n 1 --pretty=%D HEAD
%D

[Container] 2018/04/23 21:49:09 Running command git log -n 1 --pretty=%d HEAD
(HEAD, origin/caribou, origin/HEAD, caribou)

[Container] 2018/04/23 21:49:09 Running command git show -s --pretty=%d HEAD
(HEAD, origin/caribou, origin/HEAD, caribou)

```

**Comment by pvdlg** [comment]
So the problem is your version of Git is pretty old and doesn't support `%D` for the format.
I made a change to use `%d` instead that should be supported.

Could try again with your fork and the updated code on `pvdlg/env-ci#branch-detached-head`?

**Comment by coderbyheart** [comment]
fyi, I asked AWS what they are using to clone the repo: they are not cloning, but downloading the archive.

**Comment by coderbyheart** [comment]
Tested with 22530580bf6d57b6ae9dfb8743cf1388ad4acaf5 and it works.

**Comment by pvdlg** [comment]
Thanks so much for all the tests and info!

**Pull request closed without merging**
