### PR TITLE
feat(teamcity): allow anyone to set build from env

### PR DESCRIPTION
**Pull request by cyberhck**
In my case, env-ci isn't able to detect branch, but I can set it using a parameter to a env variable, it'll be quite simple, this change shouldn't break anything and should help a lot of people :)

### CODE REVIEW

**Comment by cyberhck** [comment]
on second thought, env should win everything else.

**Comment by cyberhck** [comment]
can someone please respond to this?

**Comment by pvdlg** [comment]
Where is `TEAMCITY_BUILD_BRANCH` documented? I don't see this variable anywhere in the doc.

**Comment by cyberhck** [comment]
What I meant is teamcity has different versions and different ways of determining branch, the current setup can't determine version, rather I had to use some build variable which isn't being used on this.

So if I wanted to, I could set my build to set the branch from those variables,

Right now I'm setting this env variable to `%teamcity.build.branch%`

**Comment by pvdlg** [comment]
How would you set this variable?
You must get it from somewhere. And ideally `env-ci` should get it from there directly.

**Comment by cyberhck** [comment]
consider this: I've a docker image running, inside that I want to check the branch, how'd you do it? it's under teamcity.

**Comment by pvdlg** [comment]
> consider this: I've a docker image running, inside that I want to check the branch, how'd you do it? it's under teamcity.

That's my question. How do you do it? How do you know on which branch the build is running.
You propose to `TEAMCITY_BUILD_BRANCH` yourself, but how would you do that? Where do you get the value from? If you push a commit on `dev` and it triggers a build, how do you know the name of the branch to set `TEAMCITY_BUILD_BRANCH`.

**Comment by cyberhck** [comment]
I set `TEAMCITY_BUILD_BRANCH` when I run docker, my docker script uses the %branch% or something like that,

**Pull request closed without merging**
