### PR TITLE
add woodpecker-ci support

### LINKED ISSUE #218: Support WoodpeckerCI
## Support [WoodpeckerCI](https://github.com/woodpecker-ci)

Documentation: https://woodpecker-ci.org/docs/usage/environment#built-in-environment-variables

Environment variables:
- service detection: `CI=woodpecker`
- Branch: `CI_COMMIT_SOURCE_BRANCH`
- Commit sha: `CI_COMMIT_SHA`
- Is Pull request: `CI_COMMIT_PULL_REQUEST` != ""
- Pull request: `CI_COMMIT_PULL_REQUEST`
- Build number: `CI_BUILD_NUMBER`

### PR DESCRIPTION
**Pull request by anbraten**
closes #218

### CODE REVIEW

**Review by travi — APPROVED** [review]
thanks!

**Review by 6543 — APPROVED** [review]

**Comment by 6543** [comment]
@travi wana approve CI run?

**Comment by anbraten** [comment]
@travi sorry mixed sth up again. now it should hopefully be fine. thanks

**Comment by 6543** [comment]
CI passed ;)

**Comment by travi** [comment]
> sorry mixed sth up again

no worries. thank you for the contribution!

**Comment by 6543** [comment]
Now we just need to wait for next release ;)

**Pull request merged**
