### PR TITLE
feat(Cloudbuild): Add support for Google Cloud Build

### PR DESCRIPTION
**Pull request by bijenkorf-james-wakefield**
Offering this PR to add support for Google Cloud Build.

### CODE REVIEW

**Comment by bijenkorf-james-wakefield** [comment]
@pvdlg please review this PR. Thanks in advance

**Comment by yinzara** [comment]
This is a duplicate of PR #86

**Comment by bijenkorf-james-wakefield** [comment]
> This is a duplicate of PR #86

True, will they ever get reviewed?

**Comment by yinzara** [comment]
I wish I knew. This project is used by "semantic-release" so it's pretty important.

**Comment by bijenkorf-james-wakefield** [comment]
> I wish I knew. This project is used by "semantic-release" so it's pretty important.

Same reason as to why I am waiting for it to get merged....

**Comment by pvdlg** [comment]
This PR used the environment variables `$BRANCH_NAME`, `$COMMIT_SHA`, `$TAG_NAME` etc... while the PR #86 uses `BRANCH_NAME`, `COMMIT_SHA`, `TAG_NAME`.

From the Google documentation is really not clear which one should be used. It's not even clear if those are available as actual environment variables...The doc mention "Substituting variable values" which is a way to substitute those variable in config files apparently but nothing mention environment variables.

The only way to know is to look what the environment variable look like during the build and I don't have time to set a Cloud build test account with a test repo.

Please run a build that execute the shell command `env` and provide the output. Thanks.

**Comment by bijenkorf-james-wakefield** [comment]
> Please run a build that execute the shell command `env` and provide the output. Thanks.

@pvdlg - thanks for getting around to looking at this. I agree that the documentation is not that clear. I will try to get you the information you are looking for.

**Comment by bijenkorf-james-wakefield** [comment]
@pvdlg - I have setup a test repo here:
https://github.com/bijenkorf-james-wakefield/cloudbuild-substition-variables

The substitution variables can be accessed without the $ prefix. By default they are not accessible via `env` unless they are manually mapped in the build configuration. See: https://github.com/bijenkorf-james-wakefield/cloudbuild-substition-variables/blob/master/build/cloudbuild.yaml#L10-18

In Cloud build `printenv` dumps the following:

```sh
...
BUILDER_OUTPUT=/builder/outputs
BUILD_ID=cc232635-b83e-4260-a183-7dbe5188cd31
PROJECT_ID=my-project-id
...
```
I have updated this PR given these findings. I think the mapping of the substitution variables requires some explaination. Where best to document this?

**Comment by pvdlg** [comment]
So Cloud Build doesn't offer any way to get those information with environment variables set by the service itself?
For every other CI we just use the environment variables provide by the CI itself (they all provide some) and I would rather stick to that.

I want `env-ci` to just work without having users defining custom configurations. The main goal of `env-ci` is to be used by other packages that needs information about the current CI. Requiring users to configure those variables would mean that every package that uses `env-ci` would have to specify in it's doc how to do this setup on Cloud Build.

Unfortunately, until there is way to get those info without manual user config we won't be able to support Cloud Build. Feel free to open a new issue/PR if Cloud Build start supporting default environment variables with the proper informations.

**Comment by yinzara** [comment]
@pvdlg as the author of one of the PRs, I unfortunately agree. I was not aware that the variables were not simply available. This is really a shortcoming of Cloud Build. I'm not sure what to do with this other than throw up my hands in the air.

**Comment by pvdlg** [comment]
Maybe you can open an issue/request with Cloud Build?
Having those type of info as environment variables is really a common practice. All the CIs I encounter so far (~25) do provide those.

**Comment by yinzara** [comment]
I've opened a feature suggestion with the official Google Board. Please vote!

https://googlecloudplatform.uservoice.com/forums/299943-google-cloud-platform/suggestions/38781004-use-built-in-environment-variables-by-default-inst

**Comment by bijenkorf-james-wakefield** [comment]
> I want `env-ci` to just work without having users defining custom configurations. The main goal of `env-ci` is to be used by other packages that needs information about the current CI. Requiring users to configure those variables would mean that every package that uses `env-ci` would have to specify in it's doc how to do this setup on Cloud Build.
> 
> Unfortunately, until there is way to get those info without manual user config we won't be able to support Cloud Build. Feel free to open a new issue/PR if Cloud Build start supporting default environment variables with the proper informations.

Perhaps we have missed something obvious? With the information that we have I think this is a good decision and agree. If Google wants their tools to be adopted by the developer community it would help if they follow convention.

@yinzara  I have upvoted your ticket

**Pull request closed without merging**
